name: tests

on:
  [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up rust
        uses: dtolnay/rust-toolchain@stable
        with:
          rust-version: 1.86.0

      - name: Install dependencies
        run: cargo install --path .

      - name: Run tests
        run: cargo test
